# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Build docker make and Cleanup

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/defconfig_rm.yml'
env:
   REPO_NUTTX_NAME: apache/nuttx
   REF_NUTTX_NAME: master
   REPO_APPS_NAME: apache/nuttx-apps
   REF_APPS_NAME: master
   BOARD_CONFIG_NAME: esp32s2-saola-1:mcuboot_update_agent

permissions:
  contents: read

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  LinuxCleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Show disk usage
        run: df -h

      - name: Checkout repository
        uses: actions/checkout@v6

     # - name: Free Disk Space (Ubuntu)
        # uses: ./.github/actions/free-disk-space
        # with:
          # # this might remove tools that are actually needed,
          # # if set to "true" but frees about 6 GB
          # tool-cache: false
          
          # # all of these default to true, but feel free to set to
          # # "false" if necessary for your workflow
          # android: true
          # dotnet: false
          # haskell: false
          # large-packages: false
          # docker-images: false
          # swap-storage: false
      - name: Free Up Extra Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android
      - name: Pre-build Disk Stats
        run: |
          df -h

