# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Docker Nuttx bump

permissions:
  contents: read
on: 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/docker_bump.yml'

jobs:
  build_docker_bump:
    container: ghcr.io/simbit18/nuttx-testing-ci/apache-nuttx-ci-linux:latest
    runs-on: ubuntu-latest
    steps:
      - name: System Information
        run: |
          ## system_profiler SPSoftwareDataType
          bash --version
          uname -a
      - name: Set Environment Variables
        run: |
          echo "$GITHUB_PATH"
          echo "$PATH"
          ## echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          ## echo "INSTALL_REF=${GITHUB_REF##*/}" >> "$GITHUB_ENV"
          ## echo "INSTALL_NAME=lite-xl-${GITHUB_REF##*/}-macos-${{ matrix.arch }}" >> "$GITHUB_ENV"
          ## if [[ $(uname -m) != ${{ matrix.arch }} ]]; then echo "ARCH=--cross-arch ${{ matrix.arch }}" >> "$GITHUB_ENV"; fi
          arm-none-eabi-gcc --version
          aarch64-none-elf-gcc --version
          avr32-gcc --version
      - uses: actions/checkout@v6
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install Dependencies
             # --lhelper will eliminate a warning with arm64 and libusb
        run: bash --version
      - name: Run builds
        run: |
          echo 'Checkout Source Files'
          mkdir nuttxspace
          ## ls -a
          cd nuttxspace
          # git clone --depth 1 --single-branch --branch simbit18-speed https://github.com/simbit18/nuttx.git nuttx
          # git clone --depth 1 --single-branch --branch simbit18-speed https://github.com/simbit18/nuttx-apps.git apps
          git clone --depth 1 https://github.com/apache/nuttx.git nuttx
          git clone --depth 1 https://github.com/apache/nuttx-apps.git apps
          cd nuttx
          ## ls -a
          ## git config --global --add safe.directory /github/workspace/sources/nuttx
          ## git config --global --add safe.directory /github/workspace/sources/apps
          ## cd sources/nuttx/tools/ci
          ## Configure the build
          ./tools/configure.sh -l esp32-wrover-kit:lvgl
          ## Run the build
          make V=1
