# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Manually build NuttX CI for test

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:

      repo-nuttx:
        description: What's the name of the repository nuttx (e.g. usernuttx/nuttx)?
        required: true
        type: string

      branch-nuttx:
        description: What's the name of the nuttx branch (e.g. fix-nuttx)?
        required: true
        type: string

      repo-apps:
        description: What's the name of the repository nuttx-apps (e.g. usernuttx/nuttx-apps)?
        required: true
        type: string

      branch-apps:
        description: What's the name nuttx-apps branch (e.g. fix-apps)?
        required: true
        type: string

      host-platform:
        description: Choose a host platform
        type: choice
        options:
          - linux
          - msys2
          - msvc
          - all
        default: all

concurrency:
  group: build-man-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Fetch-Source:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Target Branches
        id: gittargets
        shell: bash
        run: |
          OS_REF=""
          APPS_REF=""
          REF="refs/heads/master"
          echo "Working with ref: $REF"

      - name: Checkout nuttx repo
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repo-nuttx }}
          ref: ${{ inputs.branch-nuttx }}
          path: sources/nuttx
          fetch-depth: 1

      - name: Checkout nuttx repo tags
        run: git -C sources/nuttx fetch --tags

      - name: Checkout apps repo
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repo-apps }}
          ref: ${{ inputs.branch-apps }}
          path: sources/apps
          fetch-depth: 1

      - name: Tar sources
        run: tar zcf sources.tar.gz sources

      - name: Archive Source Bundle
        uses: actions/upload-artifact@v6
        with:
          name: source-bundle
          path: sources.tar.gz

  Linux:
    if: ${{ inputs.host-platform  == 'linux' ||  inputs.host-platform == 'all' }}
    needs: Fetch-Source
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    strategy:
      fail-fast: false
      matrix:
        boards:
         [
          "arm-01", "risc-v-01", "sim-01", "xtensa-01", "arm64-01", "x86_64-01", "other",
          "arm-02", "risc-v-02", "sim-02", "xtensa-02",
          "arm-03", "risc-v-03", "sim-03",
          "arm-04", "risc-v-04",
          "arm-05", "risc-v-05",
          "arm-06", "risc-v-06",
          "arm-07", "arm-08", "arm-09", "arm-10", "arm-11", "arm-12", "arm-13", "arm-14"
         ]
    steps:
      - name: Show Disk Space
        run: df -h

      - name: Free Disk Space (Ubuntu)
        run: |
          sudo rm -rf /usr/local/lib/android

      - name: After CLEAN-UP Disk Space
        run: df -h

      - name: Download Source Artifact
        uses: actions/download-artifact@v7
        with:
          name: source-bundle
          path: .

      - name: Extract sources
        run: tar zxf sources.tar.gz

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Pull
        run: docker pull ghcr.io/apache/nuttx/apache-nuttx-ci-linux:latest

      - name: Install NTFC
        uses: ./sources/nuttx/.github/actions/ci-container
        env:
          BLOBDIR: /tools/blobs
        with:
          run: |
            # install python venv
            apt-get update
            apt-get install -y python3 python3-dev python3-venv
            #apt-get install -y python3-dev

            # get NTFC sources
            git clone -b release-0.0.1 https://github.com/szafonimateusz-mi/nuttx-ntfc
            cd /github/workspace/nuttx-ntfc

            # install NTFC with venv
            python3 -m venv /github/workspace/nuttx-ntfc/venv
            source /github/workspace/nuttx-ntfc/venv/bin/activate
            pip3 install .
            deactivate

            # get NTFC test cases
            cd external
            git clone -b release-0.0.1 https://github.com/szafonimateusz-mi/nuttx-testing

      - name: Run builds
        uses: ./sources/nuttx/.github/actions/ci-container
        env:
          BLOBDIR: /tools/blobs
        with:
          run: |
            echo "::add-matcher::sources/nuttx/.github/gcc.json"
            export ARTIFACTDIR=`pwd`/buildartifacts
            export NTFCDIR=/github/workspace/nuttx-ntfc
            git config --global --add safe.directory /github/workspace/sources/nuttx
            git config --global --add safe.directory /github/workspace/sources/apps
            cd sources/nuttx/tools/ci
            ( sleep 7200 ; echo Killing pytest after timeout... ; pkill -f pytest )&
            ./cibuild.sh -c -A -C -N -R -S testlist/${{matrix.boards}}.dat

      - name: Post-build Disk Space
        if: always()
        run: df -h

      - uses: actions/upload-artifact@v6
        if: ${{ always() }}
        with:
          name: linux-${{matrix.boards}}-builds
          path: buildartifacts/
        continue-on-error: true

  # Test the out-of-tree build
  OOT-Build:
    needs: Linux
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Download Source Artifact
        uses: actions/download-artifact@v7
        with:
          name: source-bundle
          path: .

      - name: Extract sources
        run: tar zxf sources.tar.gz

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Export NuttX Repo SHA
        run: echo "nuttx_sha=`git -C sources/nuttx rev-parse HEAD`" >> $GITHUB_ENV

      - name: Run Out-of-Tree Build Test
        uses: ./sources/nuttx/.github/actions/ci-container
        env:
          BLOBDIR: /tools/blobs
        with:
          run: |
            echo "::add-matcher::sources/nuttx/.github/gcc.json"
            git config --global --add safe.directory /github/workspace/sources/nuttx
            git config --global --add safe.directory /github/workspace/sources/apps
            cd sources/nuttx
            ./tools/ci/cibuild-oot.sh

      - uses: actions/upload-artifact@v6
        if: ${{ always() }}
        with:
          name: oot-build-artifacts
          path: sources/apps/testing/cxx-oot-build
        continue-on-error: true

  # Run the selected msys2 Builds
  msys2:
    # if: ${{ needs.msys2-Arch.outputs.skip_all_builds != '1' }}
    if: ${{ inputs.host-platform == 'msys2' || inputs.host-platform == 'all' }}
    needs: Fetch-Source
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        boards: ["msys2"]

    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v6
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: false
          cache: false
          install: >-
            base-devel
            gcc
            gperf
            automake
            autoconf
            git
            python3
            ncurses-devel
            unzip
            zip
            tio
            zlib-devel
            cmake
            ninja
            python-pip
            vim
            genromfs

      - name: pip3 install
        run: |
          python3 -m venv --system-site-packages /usr/local
          pip3 install --root-user-action=ignore --no-cache-dir pyelftools cxxfilt kconfiglib

      - run: git config --global core.autocrlf false

      - name: Download Source Artifact
        uses: actions/download-artifact@v7
        with:
          name: source-bundle
          path: .

      - name: Extract sources
        run: tar zxf sources.tar.gz

      - name: Export NuttX Repo SHA
        run: echo "nuttx_sha=`git -C sources/nuttx rev-parse HEAD`" >> $GITHUB_ENV

      - name: Run Builds
        run: |
          echo "::add-matcher::sources/nuttx/.github/gcc.json"
          export ARTIFACTDIR=`pwd`/buildartifacts
          git config --global --add safe.directory /github/workspace/sources/nuttx
          git config --global --add safe.directory /github/workspace/sources/apps
          cd sources/nuttx/tools/ci
          ./cibuild.sh -g -i -A -C -N -R testlist/${{matrix.boards}}.dat

      - uses: actions/upload-artifact@v6
        with:
          name: msys2-${{matrix.boards}}-builds
          path: buildartifacts/
        continue-on-error: true

  # Build with MSVC in Windows native
  msvc:
    # if: ${{ needs.msvc-Arch.outputs.skip_all_builds != '1' }}
    if: ${{ inputs.host-platform == 'msvc' || inputs.host-platform == 'all' }}
    needs: Fetch-Source
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        boards: ["windows"]

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      # Set up Python environment and install kconfiglib
      - name: Set up Python and install kconfiglib
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install kconfiglib
        run: |
          pip install kconfiglib

      - run: git config --global core.autocrlf false

      - name: Download Source Artifact
        uses: actions/download-artifact@v7
        with:
          name: source-bundle
          path: .

      - name: Extract sources
        run: |
          7z x sources.tar.gz -y
          7z x sources.tar -y -snld

      - name: Run Builds
        run: |
          "ARTIFACTDIR=${{github.workspace}}\sources\buildartifacts" >> $env:GITHUB_ENV
          git config --global --add safe.directory ${{github.workspace}}\sources\nuttx
          git config --global --add safe.directory ${{github.workspace}}\sources\apps
          cd sources\nuttx\tools\ci
          .\cibuild.ps1 -n -i -A -C -N testlist\${{matrix.boards}}.dat

      - uses: actions/upload-artifact@v6
        with:
          name: msvc-builds
          path: ./sources/buildartifacts/
        continue-on-error: true
