name: Unicode
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  test-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Test  ðŸ›Ž
        run: |
          echo 'Test unicode'
          mkdir -p test-uni
          ls -a 
          cp -f unicode/test.sh test-uni/test.sh
          cd test-uni
          ls -a
          ./test.sh

      - name: Build
        run: |
          echo 'ok'